import { Machine } from "../types/Machine";

export const arrMachines1: Machine[] = [
  {
    name: "Machine 1",
    machineCode: "b-01",
    status: "Running",
    supervisor: "Alice Cooper",
    technician: "Tom Green",
    uptime: 80,
    lastMaintenance: "2025-04-01",
    nextMaintenance: "2025-07-01",
  },
  {
    name: "Machine 2",
    machineCode: "b-02",
    status: "Running",
    supervisor: "Robert Hall",
    technician: "Sandra Blue",
    uptime: 85,
    lastMaintenance: "2025-03-25",
    nextMaintenance: "2025-06-25",
  },
  {
    name: "Machine 3",
    machineCode: "b-03",
    status: "Not running",
    supervisor: "Daniel Green",
    technician: "Olivia White",
    uptime: 45,
    lastMaintenance: "2025-03-18",
    nextMaintenance: "2025-06-18",
  },
  {
    name: "Machine 4",
    machineCode: "b-04",
    status: "Running",
    supervisor: "Sophia Black",
    technician: "Benjamin Gray",
    uptime: 78,
    lastMaintenance: "2025-03-21",
    nextMaintenance: "2025-06-21",
  },
  {
    name: "Machine 5",
    machineCode: "b-05",
    status: "Not running",
    supervisor: "Chloe Adams",
    technician: "Ethan Harris",
    uptime: 32,
    lastMaintenance: "2025-03-15",
    nextMaintenance: "2025-06-15",
  },
];

export const arrMachines2: Machine[] = [
  {
    name: "Machine 6",
    machineCode: "b-06",
    status: "Not running",
    supervisor: "Alice Cooper",
    technician: "Tom Green",
    uptime: 50,
    lastMaintenance: "2025-02-25",
    nextMaintenance: "2025-05-25",
  },
  {
    name: "Machine 7",
    machineCode: "b-07",
    status: "Not running",
    supervisor: "Robert Hall",
    technician: "Sandra Blue",
    uptime: 60,
    lastMaintenance: "2025-02-18",
    nextMaintenance: "2025-05-18",
  },
  {
    name: "Machine 8",
    machineCode: "b-08",
    status: "Not running",
    supervisor: "Daniel Green",
    technician: "Olivia White",
    uptime: 20,
    lastMaintenance: "2025-02-15",
    nextMaintenance: "2025-05-15",
  },
  {
    name: "Machine 9",
    machineCode: "b-09",
    status: "Not running",
    supervisor: "Sophia Black",
    technician: "Benjamin Gray",
    uptime: 10,
    lastMaintenance: "2025-02-12",
    nextMaintenance: "2025-05-12",
  },
  {
    name: "Machine 10",
    machineCode: "b-10",
    status: "Not running",
    supervisor: "Chloe Adams",
    technician: "Ethan Harris",
    uptime: 25,
    lastMaintenance: "2025-02-10",
    nextMaintenance: "2025-05-10",
  },
];

export const arrMachines3: Machine[] = [
  {
    name: "Machine 11",
    machineCode: "b-11",
    status: "Running",
    supervisor: "Alice Cooper",
    technician: "Tom Green",
    uptime: 98,
    lastMaintenance: "2025-03-28",
    nextMaintenance: "2025-06-28",
  },
  {
    name: "Machine 12",
    machineCode: "b-12",
    status: "Running",
    supervisor: "Robert Hall",
    technician: "Sandra Blue",
    uptime: 97,
    lastMaintenance: "2025-03-22",
    nextMaintenance: "2025-06-22",
  },
  {
    name: "Machine 13",
    machineCode: "b-13",
    status: "Running",
    supervisor: "Daniel Green",
    technician: "Olivia White",
    uptime: 94,
    lastMaintenance: "2025-03-20",
    nextMaintenance: "2025-06-20",
  },
  {
    name: "Machine 14",
    machineCode: "b-14",
    status: "Running",
    supervisor: "Sophia Black",
    technician: "Benjamin Gray",
    uptime: 91,
    lastMaintenance: "2025-03-18",
    nextMaintenance: "2025-06-18",
  },
  {
    name: "Machine 15",
    machineCode: "b-15",
    status: "Running",
    supervisor: "Chloe Adams",
    technician: "Ethan Harris",
    uptime: 89,
    lastMaintenance: "2025-03-10",
    nextMaintenance: "2025-06-10",
  },
];

export const arrMachines4: Machine[] = [
  {
    name: "Machine 16",
    machineCode: "b-16",
    status: "Running",
    supervisor: "David Moon",
    technician: "Lily Fox",
    uptime: 82,
    lastMaintenance: "2025-03-19",
    nextMaintenance: "2025-06-19",
  },
  {
    name: "Machine 17",
    machineCode: "b-17",
    status: "Not running",
    supervisor: "Nancy Hill",
    technician: "Daniel Steel",
    uptime: 33,
    lastMaintenance: "2025-03-12",
    nextMaintenance: "2025-06-12",
  },
  {
    name: "Machine 18",
    machineCode: "b-18",
    status: "Running",
    supervisor: "Jack Gold",
    technician: "Ella Moore",
    uptime: 87,
    lastMaintenance: "2025-03-10",
    nextMaintenance: "2025-06-10",
  },
  {
    name: "Machine 19",
    machineCode: "b-19",
    status: "Not running",
    supervisor: "Nina Bright",
    technician: "Gabe Green",
    uptime: 70,
    lastMaintenance: "2025-03-05",
    nextMaintenance: "2025-06-05",
  },
  {
    name: "Machine 20",
    machineCode: "b-20",
    status: "Running",
    supervisor: "Victor Black",
    technician: "Rose Walker",
    uptime: 77,
    lastMaintenance: "2025-03-01",
    nextMaintenance: "2025-06-01",
  },
];

export const arrMachines5: Machine[] = [
  {
    name: "Machine 21",
    machineCode: "b-21",
    status: "Running",
    supervisor: "Lucas Lee",
    technician: "Megan White",
    uptime: 90,
    lastMaintenance: "2025-02-28",
    nextMaintenance: "2025-05-28",
  },
  {
    name: "Machine 22",
    machineCode: "b-22",
    status: "Not running",
    supervisor: "Evan Clark",
    technician: "Zoe Blue",
    uptime: 35,
    lastMaintenance: "2025-02-22",
    nextMaintenance: "2025-05-22",
  },
  {
    name: "Machine 23",
    machineCode: "b-23",
    status: "Running",
    supervisor: "Grace Harris",
    technician: "Luke Taylor",
    uptime: 83,
    lastMaintenance: "2025-02-18",
    nextMaintenance: "2025-05-18",
  },
  {
    name: "Machine 24",
    machineCode: "b-24",
    status: "Not running",
    supervisor: "Oscar Brown",
    technician: "Kimberly Green",
    uptime: 25,
    lastMaintenance: "2025-02-15",
    nextMaintenance: "2025-05-15",
  },
  {
    name: "Machine 25",
    machineCode: "b-25",
    status: "Running",
    supervisor: "Lily Thompson",
    technician: "Aidan White",
    uptime: 92,
    lastMaintenance: "2025-02-10",
    nextMaintenance: "2025-05-10",
  },
];

export const arrPlants = [
  {
    id: 401,
    name: "Plant 1",
    status: "Active",
    health: 85,
    maintenance: 30,
    location: "Leuvensestraat 56, 8970 Leuven",
    machines: arrMachines1,
    verantwoordelijke: "Alice Cooper",
    currentProduction: 45,
    efficiencyRate: 40,
  },
  {
    id: 301,
    name: "Plant 2",
    status: "Inactive",
    health: 70,
    maintenance: 15,
    location: "Gentstraat 45, 9000 Gent",
    machines: arrMachines2,
    verantwoordelijke: "John Smith",
    currentProduction: 40,
    efficiencyRate: 38,
  },
  // {
  //   id: 3,
  //   name: "Plant 3",
  //   status: "Active",
  //   health: 95,
  //   maintenance: 60,
  //   location: "789 Birch Rd, 9101 Pinehill",
  //   machines: arrMachines3,
  //   verantwoordelijke: "Robert Hall",
  //   currentProduction: 55,
  //   efficiencyRate: 45,
  // },
  // {
  //   id: 4,
  //   name: "Plant 4",
  //   status: "Active",
  //   health: 80,
  //   maintenance: 20,
  //   location: "101 Pine St, 1122 Hilltop",
  //   machines: arrMachines4,
  //   verantwoordelijke: "Sophie Turner",
  //   currentProduction: 50,
  //   efficiencyRate: 50,
  // },
  // {
  //   id: 5,
  //   name: "Plant 5",
  //   status: "Inactive",
  //   health: 60,
  //   maintenance: 10,
  //   location: "202 Elm St, 2334 Redwood",
  //   machines: arrMachines5,
  //   verantwoordelijke: "James Bond",
  //   currentProduction: 25,
  //   efficiencyRate: 28,
  // },
];
